#Requires -Version 7.0

<#
.SYNOPSIS
    Regenerates a repo's AGENTS.md from the shared conventions block plus its
    own local conventions.

.DESCRIPTION
    AGENTS.md is generated, not hand-edited: it concatenates the project-wide
    shared conventions (this repo's defaults/AGENTS.shared.md) with a repo's
    own AGENTS.local.md, so shared rules stay identical everywhere while each
    repo keeps room for its own. Cross-tool readers (Cursor, Copilot, Codex,
    Gemini CLI, ...) get this file as-is. Claude Code instead imports both
    source files live via CLAUDE.md's @path syntax — see
    homelab-infra/decisions/ for why both mechanisms exist side by side.

.PARAMETER SharedPath
    Path to the canonical defaults/AGENTS.shared.md.

.PARAMETER LocalPath
    Path to the calling repo's own AGENTS.local.md.

.PARAMETER OutputPath
    Where to write the generated AGENTS.md.
#>

param(
    [Parameter(Mandatory)]
    [string]$SharedPath,

    [Parameter(Mandatory)]
    [string]$LocalPath,

    [Parameter(Mandatory)]
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not (Test-Path $SharedPath)) {
    throw "Shared conventions file not found: $SharedPath"
}
if (-not (Test-Path $LocalPath)) {
    throw "Local conventions file not found: $LocalPath"
}

$shared = (Get-Content $SharedPath -Raw).TrimEnd()
$local = (Get-Content $LocalPath -Raw).TrimEnd()

$header = @'
<!--
  GENERATED FILE — do not edit by hand.
  Shared section source: ps-shared-workflows/defaults/AGENTS.shared.md
  Repo-specific section source: AGENTS.local.md
  Regenerated by: ps-shared-workflows/.github/workflows/agents-md-sync.yml
  (Claude Code reads AGENTS.local.md and AGENTS.shared.md directly, live,
  via CLAUDE.md's @path imports — this file is for every other tool.)
-->

'@

$body = @"
<!-- BEGIN SHARED (ps-shared-workflows/defaults/AGENTS.shared.md) -->
$shared
<!-- END SHARED -->

<!-- BEGIN REPO-SPECIFIC (AGENTS.local.md) -->
$local
<!-- END REPO-SPECIFIC -->
"@

Set-Content -Path $OutputPath -Value ($header + $body) -Encoding UTF8 -NoNewline
Write-Host "Wrote $OutputPath"
